### ISSUE TITLE
Containerized ticketd

### ISSUE THREAD

**Issue by qyvlik** [willemt/ticketd#16]
# Dockerfile 

```Dockerfile
FROM gcc:8

RUN apt update && \
  apt install cmake python-simplejson  -y

WORKDIR /ticketd

COPY ticketd/ /ticketd

RUN make libuv

# install libuv for libh2o
RUN cd deps/libuv && \
  make install && \
  cd /ticketd

RUN make libh2o

# error: variably modified 'leader_host' at file scope
RUN sed -i 's/strlen("111.111.111.111")/15/g' src/main.c

RUN make

# http port
EXPOSE 8001

# raft port
EXPOSE 9001

# ticketd start --id 1 --raft_port 9001 --http_port 8001
ENTRYPOINT ["/ticketd/build/ticketd"]
```

# docker-compose.yml

```yml
version: '2'

services:

  ticketd1:
    image: ticketd
    command: start --id 1 --raft_port 9001 --http_port 8001
    network_mode: host

  ticketd2:
    image: ticketd
    command: join 127.0.0.1:9001 --id 2 --raft_port 9002 --http_port 8002
    network_mode: host
    depends_on:
      - ticketd1
      
  ticketd3:
    image: ticketd
    command: join 127.0.0.1:9001 --id 3 --raft_port 9003 --http_port 8003
    network_mode: host
    depends_on:
      - ticketd1
```

```bash
git clone https://github.com/willemt/ticketd
docker build -t ticketd .
docker-compose up -d

curl --request POST -i -L 127.0.0.1:8001
curl --request POST -i -L 127.0.0.1:8002
curl --request POST -i -L 127.0.0.1:8003
```
